import './globals.css';
import { Open_Sans } from 'next/font/google';
import { PageHeader, PageFooter } from '@components/layout';

const sans = Open_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={sans.className}>
      <body className="mx-auto flex min-h-screen w-full max-w-7xl flex-col px-8">
        <PageHeader />
        <main className="grow">{children}</main>
        <PageFooter />
      </body>
    </html>
  );
}
