import './globals.css';
import { Open_Sans } from 'next/font/google';
import { PageHeader, PageFooter } from '@components/layout';

const sans = Open_Sans({ subsets: ['latin'] });

export const metadata = {
  title: "Dotori Jung's Blog",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={sans.className}>
      <body className="flex min-h-screen flex-col bg-[#f8f8f8]">
        <PageHeader />
        <main className="mx-auto w-full max-w-7xl grow p-8">{children}</main>
        <PageFooter />
      </body>
    </html>
  );
}
